AWSTemplateFormatVersion: 2010-09-09
Outputs:
  JobStatusUrl:
    Value: !Ref JobStatus
  WorkerProfileArn:
    Value: !GetAtt WorkerProfile.Arn
Resources:
  WorkerProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Roles:
        - !Ref JobRole
  JobStatus:
    Type: 'AWS::SQS::Queue'
    Properties: {}
  JobRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'
        - 'arn:aws:iam::aws:policy/AmazonSQSFullAccess'
