AWSTemplateFormatVersion: 2010-09-09
Outputs:
  jobQueueUrl:
    Value: !Ref JobQueue
  workerProfileArn:
    Value: !GetAtt WorkerProfile.Arn
  logGroupName:
    Value: !Ref JobLogs
Resources:
  JobLogs:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      RetentionInDays: 30
  WorkerProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Roles:
        - !Ref WorkerRole
  JobQueue:
    Type: 'AWS::SQS::Queue'
    Properties: {}
  WorkerRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'
        - 'arn:aws:iam::aws:policy/AmazonSQSFullAccess'
        - 'arn:aws:iam::aws:policy/CloudWatchLogsFullAccess'
