AWSTemplateFormatVersion: 2010-09-09
Outputs:
  jobQueueUrl:
    Value: !Ref JobQueue
  workerProfileArn:
    Value: !GetAtt WorkerProfile.Arn
  logGroupName:
    Value: !Ref JobLogs
  securityGroupId:
    Value: !GetAtt SecurityGroup.GroupId
  group:
    Value: !Ref IAMGroup
Resources:
  IAMGroup:
    Type: 'AWS::IAM::Group'
    Properties:
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'
        - 'arn:aws:iam::aws:policy/AmazonSQSFullAccess'
        - 'arn:aws:iam::aws:policy/AmazonEC2FullAccess'
        - 'arn:aws:iam::aws:policy/CloudWatchLogsReadOnlyAccess'
        - 'arn:aws:iam::aws:policy/AWSCloudFormationReadOnlyAccess'
      Policies:
        - PolicyName: PassRolePolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: 'iam:PassRole'
                Resource: '*'
  SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'all inbound closed'
  JobLogs:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      RetentionInDays: 30
  WorkerProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Roles:
        - !Ref WorkerRole
  JobQueue:
    Type: 'AWS::SQS::Queue'
    Properties:
      VisibilityTimeout: 0
      Tags:
        - 
          Key: hyperdrive.stack
          Value: !Ref "AWS::StackName"
  WorkerRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'
        - 'arn:aws:iam::aws:policy/AmazonSQSFullAccess'
        - 'arn:aws:iam::aws:policy/CloudWatchLogsFullAccess'
